"""
Reporting tools — write HTML reports, trace packs, final packets, and audit log events.
"""
import datetime
import json
import os
from typing import Any, Dict, List, Optional, Type
from crewai.tools import BaseTool
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ensure_dir(path: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)


def _ts() -> str:
    return datetime.datetime.utcnow().isoformat() + "Z"


# ---------------------------------------------------------------------------
# Embedded Jinja2-style HTML template (rendered with string .format)
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Document AI Testing Report — {run_id}</title>
  <style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 0; padding: 0; background: #f5f7fa; color: #222; }}
    .header {{ background: #1F4E79; color: #fff; padding: 24px 32px; }}
    .header h1 {{ margin: 0 0 8px; font-size: 1.6rem; }}
    .header .meta {{ font-size: 0.85rem; opacity: 0.85; }}
    .badge {{ display: inline-block; padding: 6px 20px; border-radius: 4px; font-weight: bold;
              font-size: 1.1rem; letter-spacing: 1px; margin: 0 8px; }}
    .badge-PASS {{ background: #1e8a44; color: #fff; }}
    .badge-WARN {{ background: #e6a817; color: #fff; }}
    .badge-BLOCK {{ background: #c0392b; color: #fff; }}
    .badge-UNKNOWN {{ background: #888; color: #fff; }}
    .section {{ background: #fff; margin: 20px 32px; padding: 20px 24px; border-radius: 6px;
                box-shadow: 0 1px 4px rgba(0,0,0,0.08); }}
    .section h2 {{ margin-top: 0; color: #1F4E79; font-size: 1.1rem; border-bottom: 2px solid #e8edf3; padding-bottom: 8px; }}
    table {{ border-collapse: collapse; width: 100%; font-size: 0.9rem; }}
    th {{ background: #1F4E79; color: #fff; padding: 8px 12px; text-align: left; }}
    td {{ padding: 7px 12px; border-bottom: 1px solid #e8edf3; }}
    tr:hover td {{ background: #f0f4fa; }}
    .improvement {{ color: #1e8a44; font-weight: bold; }}
    .regression {{ color: #c0392b; font-weight: bold; }}
    .neutral {{ color: #888; }}
    ul {{ margin: 0; padding-left: 20px; }}
    li {{ margin: 4px 0; }}
    .routing {{ font-size: 1.0rem; padding: 12px; border-left: 5px solid #1F4E79;
                background: #eef4fb; border-radius: 0 4px 4px 0; }}
    .footer {{ text-align: center; padding: 16px; font-size: 0.78rem; color: #aaa; }}
  </style>
</head>
<body>
<div class="header">
  <h1>Document AI Agentic Testing Report</h1>
  <div class="meta">
    Run ID: <strong>{run_id}</strong> &nbsp;|&nbsp;
    Generated: <strong>{generated_at}</strong> &nbsp;|&nbsp;
    Transactions Evaluated: <strong>{transaction_count}</strong>
  </div>
  <div style="margin-top:12px;">
    Verdict: <span class="badge badge-{verdict}">{verdict}</span>
  </div>
</div>

<div class="section">
  <h2>Metrics Summary</h2>
  <table>
    <tr><th>Metric</th><th>Baseline</th><th>Candidate</th><th>Delta</th></tr>
    {metrics_rows}
  </table>
</div>

<div class="section">
  <h2>Improvements</h2>
  {improvements_html}
</div>

<div class="section">
  <h2>Regressions</h2>
  {regressions_html}
</div>

<div class="section">
  <h2>Hidden Risks</h2>
  {hidden_risks_html}
</div>

<div class="section">
  <h2>Root Causes</h2>
  {root_causes_html}
</div>

<div class="section">
  <h2>Patch Candidates</h2>
  {patch_candidates_html}
</div>

<div class="section">
  <h2>Routing Decision</h2>
  <div class="routing">{routing_decision}</div>
</div>

<div class="footer">Generated by Document AI Agentic Testing System &mdash; {generated_at}</div>
</body>
</html>
"""


def _render_list(items: List[Any], empty_msg: str = "None.") -> str:
    if not items:
        return f"<p>{empty_msg}</p>"
    lis = "".join(f"<li>{_escape(str(item))}</li>" for item in items)
    return f"<ul>{lis}</ul>"


def _escape(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def _render_metrics_rows(metrics: Dict[str, Any]) -> str:
    rows = []
    for key, val in metrics.items():
        if isinstance(val, dict):
            b = _escape(str(val.get("baseline", "")))
            c = _escape(str(val.get("candidate", "")))
            d_raw = val.get("delta")
            try:
                d_f = float(d_raw)
                d_cls = "improvement" if d_f > 0 else "regression" if d_f < 0 else "neutral"
                d_str = f'<span class="{d_cls}">{d_f:+.4f}</span>'
            except (TypeError, ValueError):
                d_str = _escape(str(d_raw or ""))
            rows.append(f"<tr><td>{_escape(key)}</td><td>{b}</td><td>{c}</td><td>{d_str}</td></tr>")
        else:
            rows.append(f"<tr><td>{_escape(key)}</td><td colspan='3'>{_escape(str(val))}</td></tr>")
    return "\n    ".join(rows) if rows else "<tr><td colspan='4'>No metrics available.</td></tr>"


# ---------------------------------------------------------------------------
# WriteHtmlReportTool
# ---------------------------------------------------------------------------

class WriteHtmlReportInput(BaseModel):
    run_state: Dict[str, Any] = Field(
        ...,
        description=(
            "Full run state dict. Expected keys: run_id, workspace_path, verdict "
            "(PASS|WARN|BLOCK), transaction_count, metrics (dict), improvements (list), "
            "regressions (list), hidden_risks (list), root_causes (list), "
            "patch_candidates (list), routing_decision (str)."
        ),
    )


class WriteHtmlReportTool(BaseTool):
    name: str = "write_html_report"
    description: str = (
        "Generate an HTML testing report from the run_state dict and write it to "
        "<workspace_path>/report.html. Includes verdict badge, metrics table, "
        "improvements, regressions, hidden risks, root causes, patch candidates, "
        "and routing decision. Returns JSON with status and path."
    )
    args_schema: Type[BaseModel] = WriteHtmlReportInput

    def _run(self, run_state: Dict[str, Any]) -> str:
        try:
            workspace_path = run_state.get("workspace_path", ".")
            report_path = os.path.join(workspace_path, "report.html")
            os.makedirs(workspace_path, exist_ok=True)

            run_id = run_state.get("run_id", "UNKNOWN")
            verdict = str(run_state.get("verdict", "UNKNOWN")).upper()
            if verdict not in ("PASS", "WARN", "BLOCK"):
                verdict = "UNKNOWN"
            transaction_count = run_state.get("transaction_count", 0)
            generated_at = _ts()

            metrics = run_state.get("metrics") or {}
            improvements = run_state.get("improvements") or []
            regressions = run_state.get("regressions") or []
            hidden_risks = run_state.get("hidden_risks") or []
            root_causes = run_state.get("root_causes") or []
            patch_candidates = run_state.get("patch_candidates") or []
            routing_decision = _escape(str(run_state.get("routing_decision", "No routing decision provided.")))

            html = _HTML_TEMPLATE.format(
                run_id=_escape(run_id),
                verdict=verdict,
                generated_at=generated_at,
                transaction_count=transaction_count,
                metrics_rows=_render_metrics_rows(metrics),
                improvements_html=_render_list(improvements, "No improvements detected."),
                regressions_html=_render_list(regressions, "No regressions detected."),
                hidden_risks_html=_render_list(hidden_risks, "No hidden risks detected."),
                root_causes_html=_render_list(root_causes, "No root causes identified."),
                patch_candidates_html=_render_list(patch_candidates, "No patch candidates."),
                routing_decision=routing_decision,
            )

            with open(report_path, "w", encoding="utf-8") as f:
                f.write(html)

            return json.dumps({"status": "ok", "path": report_path, "verdict": verdict})
        except Exception as e:
            return json.dumps({"error": str(e), "tool": "write_html_report"})


# ---------------------------------------------------------------------------
# WriteTracePackTool
# ---------------------------------------------------------------------------

class WriteTracePackInput(BaseModel):
    run_state: Dict[str, Any] = Field(
        ...,
        description=(
            "Full run state dict. Expected keys: workspace_path, full_maestro_input, "
            "selected_transactions (list), all_agent_outputs (dict), "
            "rerun_requests (list), final_packet (dict)."
        ),
    )


class WriteTracePackTool(BaseTool):
    name: str = "write_trace_pack"
    description: str = (
        "Write a complete trace pack JSON file to <workspace_path>/trace_pack.json. "
        "Contains full_maestro_input, selected_transactions, all_agent_outputs, "
        "rerun_requests, and final_packet for audit and reproducibility."
    )
    args_schema: Type[BaseModel] = WriteTracePackInput

    def _run(self, run_state: Dict[str, Any]) -> str:
        try:
            workspace_path = run_state.get("workspace_path", ".")
            os.makedirs(workspace_path, exist_ok=True)
            trace_path = os.path.join(workspace_path, "trace_pack.json")

            trace_pack = {
                "generated_at_utc": _ts(),
                "run_id": run_state.get("run_id", "UNKNOWN"),
                "full_maestro_input": run_state.get("full_maestro_input"),
                "selected_transactions": run_state.get("selected_transactions") or [],
                "all_agent_outputs": run_state.get("all_agent_outputs") or {},
                "rerun_requests": run_state.get("rerun_requests") or [],
                "final_packet": run_state.get("final_packet") or {},
            }

            with open(trace_path, "w", encoding="utf-8") as f:
                json.dump(trace_pack, f, indent=2, default=str)

            return json.dumps({"status": "ok", "path": trace_path})
        except Exception as e:
            return json.dumps({"error": str(e), "tool": "write_trace_pack"})


# ---------------------------------------------------------------------------
# WriteFinalPacketTool
# ---------------------------------------------------------------------------

class WriteFinalPacketInput(BaseModel):
    workspace_path: str = Field(..., description="Root workspace directory for this run.")
    final_packet: Dict[str, Any] = Field(
        ...,
        description=(
            "The complete final packet to persist. Should contain all fields required "
            "by the downstream consumer (e.g., UiPath Maestro orchestrator)."
        ),
    )


class WriteFinalPacketTool(BaseTool):
    name: str = "write_final_packet"
    description: str = (
        "Write the final packet dict to <workspace_path>/latest_run.json. "
        "This file is the canonical output consumed by downstream orchestration. "
        "Returns JSON with status and path."
    )
    args_schema: Type[BaseModel] = WriteFinalPacketInput

    def _run(self, workspace_path: str, final_packet: Dict[str, Any]) -> str:
        try:
            os.makedirs(workspace_path, exist_ok=True)
            output_path = os.path.join(workspace_path, "latest_run.json")

            payload = {
                "written_at_utc": _ts(),
                **final_packet,
            }

            with open(output_path, "w", encoding="utf-8") as f:
                json.dump(payload, f, indent=2, default=str)

            return json.dumps({"status": "ok", "path": output_path})
        except Exception as e:
            return json.dumps({"error": str(e), "tool": "write_final_packet"})


# ---------------------------------------------------------------------------
# WriteAuditLogEventTool
# ---------------------------------------------------------------------------

class WriteAuditLogEventInput(BaseModel):
    audit_log_path: str = Field(..., description="Absolute path to the audit log workbook.")
    event_row: Dict[str, Any] = Field(
        ...,
        description=(
            "Event row dict with fields: RunID, EventID, AgentName, EventType, "
            "Timestamp, DurationSeconds, InputRef, OutputRef, Summary, Status."
        ),
    )


class WriteAuditLogEventTool(BaseTool):
    name: str = "write_audit_log_event"
    description: str = (
        "Append an audit log event row to the AgentEvents sheet of the audit log workbook. "
        "Creates the workbook and sheet if they do not exist. Returns JSON with status."
    )
    args_schema: Type[BaseModel] = WriteAuditLogEventInput

    def _run(self, audit_log_path: str, event_row: Dict[str, Any]) -> str:
        try:
            from .excel_writer import AppendRowsTool
            appender = AppendRowsTool()
            # Ensure standard columns are present with defaults
            normalised = {
                "RunID": event_row.get("RunID", ""),
                "EventID": event_row.get("EventID", ""),
                "AgentName": event_row.get("AgentName", ""),
                "EventType": event_row.get("EventType", ""),
                "Timestamp": event_row.get("Timestamp", _ts()),
                "DurationSeconds": event_row.get("DurationSeconds", 0.0),
                "InputRef": event_row.get("InputRef", ""),
                "OutputRef": event_row.get("OutputRef", ""),
                "Summary": event_row.get("Summary", ""),
                "Status": event_row.get("Status", "OK"),
            }
            result = appender._run(
                workbook_path=audit_log_path,
                sheet_name="AgentEvents",
                rows=[normalised],
            )
            return result
        except Exception as e:
            return json.dumps({"error": str(e), "tool": "write_audit_log_event"})


# ---------------------------------------------------------------------------
# Convenience instances
# ---------------------------------------------------------------------------
write_html_report = WriteHtmlReportTool()
write_trace_pack = WriteTracePackTool()
write_final_packet = WriteFinalPacketTool()
write_audit_log_event = WriteAuditLogEventTool()
